apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: java-quarkus-kfkuytqj 
  janus-idp.io/tekton: java-quarkus-kfkuytqj
  backstage.io/kubernetes-id: java-quarkus-kfkuytqj
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: java-quarkus-kfkuytqj
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml