apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: java-quarkus-kfkuytqj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-kfkuytqj 
  name: java-quarkus-kfkuytqj
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: java-quarkus-kfkuytqj
    weight: 100 
