apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: java-quarkus-kfkuytqj
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/java-quarkus-kfkuytqj:84f4597645d15aa358a5ed6dde1d22ae19c7cbc5@sha256:42b904b0a8b4e89cdf42a90f5b9bb1890e89405769bf2e6af2eed45a0a84c164
        name: container-image  
